// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace SceneEditorExtensionExample.Rendering
{
    public static partial class EnvironmentWindSourcesKeys
    {
        public static readonly ValueParameterKey<float> WindAmbient_WindSpeed = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector2> WindDirectional_WindDirectionXZ = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<float> WindDirectional_WindMaxSpeed = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> WindDirectional_WindCurrentStrength = ParameterKeys.NewValue<float>();
    }
}
