<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;DebugExGameEditor</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='DebugExGameEditor|net10.0|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Stride.Core" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Core.Serialization" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Engine" Version="4.3.0.2507" />
  </ItemGroup>
</Project>