// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace SceneEditorExtensionExample.Rendering
{
    public static partial class MaterialGrassMeshDisplacementKeys
    {
        public static readonly ObjectParameterKey<SamplerState> WindNoiseMapSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<Texture> WindNoiseMap = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<float> AmbientWindNoiseMapWorldLength = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> AmbientWindMaxDisplacementY = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> ActiveWindNoiseMapWorldLength = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> ActiveWindMaxDisplacementXZ = ParameterKeys.NewValue<float>();
    }
}
