<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Stride.Engine" Version="4.2.0.2374" />
    <PackageReference Include="Stride.Video" Version="4.2.0.2374" />
    <PackageReference Include="Stride.Physics" Version="4.2.0.2374" />
    <PackageReference Include="Stride.Navigation" Version="4.2.0.2374" />
    <PackageReference Include="Stride.Particles" Version="4.2.0.2374" />
    <PackageReference Include="Stride.UI" Version="4.2.0.2374" />
    <PackageReference Include="Stride.Core.Assets.CompilerApp" Version="4.2.0.2374" IncludeAssets="build;buildTransitive" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Effects\DecalShader.sdsl.cs">
      <DesignTime>True</DesignTime>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Effects\ObjectInfoInputShader.sdsl.cs">
      <DesignTime>True</DesignTime>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Effects\ObjectInfoOutputEffect.sdfx.cs">
      <DesignTime>True</DesignTime>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Effects\ObjectInfoOutputShader.sdsl.cs">
      <DesignTime>True</DesignTime>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Effects\ObjectInfoStrideBaseEffect.sdfx.cs">
      <DesignTime>True</DesignTime>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Effects\DecalShader.sdsl">
      <LastGenOutput>DecalShader.sdsl.cs</LastGenOutput>
    </None>
    <None Update="Effects\ObjectInfoInputShader.sdsl">
      <LastGenOutput>ObjectInfoInputShader.sdsl.cs</LastGenOutput>
    </None>
    <None Update="Effects\ObjectInfoOutputEffect.sdfx">
      <LastGenOutput>ObjectInfoOutputEffect.sdfx.cs</LastGenOutput>
    </None>
    <None Update="Effects\ObjectInfoOutputShader.sdsl">
      <LastGenOutput>ObjectInfoOutputShader.sdsl.cs</LastGenOutput>
    </None>
    <None Update="Effects\ObjectInfoStrideBaseEffect.sdfx">
      <LastGenOutput>ObjectInfoStrideBaseEffect.sdfx.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>